update error handle

diff --git a/.github/actions/repo-check/action.yml b/.github/actions/repo-check/action.yml
--- a/.github/actions/repo-check/action.yml
+++ b/.github/actions/repo-check/action.yml
@@ -26,20 +26,18 @@ runs:
         owner_name: ${{ inputs.owner-name }}
       run: |
         set +e
-        gh api \
-          "repos/$owner_name/$repo_name" \
-          -H "Accept: application/vnd.github.v3+json" 
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          --include \
-          -X GET \
-          -o repo_get_output.json
-        if [ $? -ne 0 ]; then
-          echo " API call failed, but we are continuing execution..."
-          printf '{"response_status":"$?"}' > repo_get_output.json
-          response_status="$?"
-          echo $response_status
+        STATUS_CODE=$(curl -o repo_get_output.json -s -w "%{http_code}\n" -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $GH_TOKEN" "https://api.github.com/repos/$owner_name/$repo_name")
+        if [ $STATUS_CODE -eq 404 ]; then
+          echo "API call failed with status code $STATUS_CODE, but we are continuing execution..."
+          printf '{"response_status":"%s"}' $STATUS_CODE > repo_get_output.json
+        elif [ $STATUS_CODE -eq 200 ]; then
+          echo "API call succeeded with status code $STATUS_CODE"
+          printf '{"response_status":"%s"}' $STATUS_CODE > repo_get_output.json
+        else
+          echo "API call failed with status code $STATUS_CODE"
+          exit 1
         fi  
-        set -e  
+        set -e   
     - name: Set output  
       shell: bash
       id: set_output
