update workfloe to do test and get output oc check before calling action

diff --git a/.github/workflows/create_new_repo.yml b/.github/workflows/create_new_repo.yml
--- a/.github/workflows/create_new_repo.yml
+++ b/.github/workflows/create_new_repo.yml
@@ -13,17 +13,38 @@ on:
         default: "Creation of new test repo using api calls in GitHub"
 
 jobs:
-  repo_test:
+  repo_check_test:
    runs-on: ubuntu-latest
    name: "Check Repo Existence" 
    steps:
     - name: Run Check out
       uses: actions/checkout@v4
     - id: repo-check
-      uses: ./.github/actions/repo-check
-      with:
+      shell: bash
+      env:
         pat-token: ${{ secrets.API_PAT_TOKEN }}
         repo-name: ${{ github.event.inputs.repository-name }}
         owner-name: ${{ github.repository_owner }}
         repo-description: ${{ github.event.inputs.repository_description }}
+      run: |
+        set +e
+        STATUS_CODE=$(curl -o repo_get_output.json -s -w "%{http_code}\n" -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $GH_TOKEN" "https://api.github.com/repos/$owner_name/$repo_name")
+        if [ $STATUS_CODE -eq 404 ]; then
+          echo "API call failed with status code $STATUS_CODE, but we are continuing execution..."
+          printf '{"response_status":"%s"}' $STATUS_CODE > repo_get_output.json
+        elif [ $STATUS_CODE -eq 200 ]; then
+          echo "API call succeeded with status code $STATUS_CODE"
+          printf '{"response_status":"%s"}' $STATUS_CODE > repo_get_output.json
+        else
+          echo "API call failed with status code $STATUS_CODE"
+          exit 1
+        fi  
+        set -e
+        echo "repo_get_output=$(cat repo_get_output.json) >> GITHUB_OUTPUT"   
  
+      - name: Test output
+      shell: bash
+      id: test_repo_output
+      run: |
+        echo "Running tests..."
+        echo "Repo check output: ${{ steps.repo_get_call.outputs.repo_get_output }}" 
